<a href="https://colab.research.google.com/github/physicsme1729/Numerical-methods-in-physics/blob/main/7_swarup_kumar_Giri_phy_P745.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Problem 1:***

Use Gaussian elimination or LU decomposition (without and with pivoting) for:
$$\left(\begin{array}{cccc|c}  
 4 & 4 & 8 & 4 & 1 \\  
 4 & 5 & 3 & 7 & 2  \\
 8 & 3 & 9 & 9 & 3\\
 4 & 7 & 9 & 5 & 4\\
\end{array}\right)
$$
Does pivoting help in any way? What are your conclusions about this matrix? You
sometimes hear the advice that, since the problem arises from one of the $U_{ii}$'s being zero, you should replace it with a small number, say $10^{-20}$. Does this work?

ANS:-

# ***I do the whole calculation  using Gaussian elimination for both cases with and without pivoting ...***

Let's first perform Gaussian elimination without pivoting and then with pivoting for the given matrix:

# **Gaussian Elimination Without Pivoting:**

Step 1: Divide the first row by 4 to make the first element 1.
$$\left(\begin{array}{cccc|c}  
 1 & 1 & 2 & 1 & 1/4 \\  
 4 & 5 & 3 & 7 & 2  \\
 8 & 3 & 9 & 9 & 3\\
 4 & 7 & 9 & 5 & 4\\
\end{array}\right)
$$
Step 2: Subtract 4 times the first row from the second row, 8 times the first row from the third row, and 4 times the first row from the fourth row to make the first column below the 1 in the first row all zeros.
$$\left(\begin{array}{cccc|c}  
 1 & 1 & 2 & 1 & 1/4 \\  
 0 & 1 & -5 & 3 & 1  \\
 0 & -5 & -7 & 1 & 1\\
 0 & 3 & 1 & 1 & 3\\
\end{array}\right)
$$
Step 3:  Add 5 times the second row to the third row and subtract 3 times the second row from the fourth row to make all the elements below the 1 in the second row zero.
$$\left(\begin{array}{cccc|c}  
 1 & 1 & 2 & 1 & 1/4 \\  
 0 & 1 & -5 & 3 & 1  \\
 0 & 0 & -32 & 16 & 6\\
 0 & 0 & 16 & -8 & 0\\
\end{array}\right)
$$
 step 4:Divide the third row by -32 to make the leading coefficient in the third row 1.
 $$\left(\begin{array}{cccc|c}  
 1 & 1 & 2 & 1 & 1/4 \\  
 0 & 1 & -5 & 3 & 1  \\
 0 & 0 & 1 & -1/2 & -3/16\\
 0 & 0 & 16 & -8 & 0\\
\end{array}\right)
$$
Step 5: Subtract 16 times the third row from the fourth row to make all the elements below the 1 in the third row zero.
$$\left(\begin{array}{cccc|c}  
 1 & 1 & 2 & 1 & 1/4 \\  
 0 & 1 & -5 & 3 & 1  \\
 0 & 0 & 1 & -1/2 & -3/16\\
 0 & 0 & 0 & 0 & 3\\
\end{array}\right)
$$


Now, let's proceed with the conclusion and the advice given:

# ***1.CONCLUSOIN:***
In the without pivoting case, we've successfully reduced the matrix to row-echelon form. However, we have reached a point where the last row indicates that there are inconsistent equations. The system is inconsistent because the equation  cannot be satisfied, which means there is no solution to the system.

# ***2.ADVICE:***
The problem arose because one of the diagonal elements ($U_{ii}$) became zero during the elimination process. The advice to replace it with a small number (e.g., $10^{-20}$) is related to numerical stability. This can help avoid division by very small numbers, which might lead to numerical errors in some cases. However, in practice, it won't change the fundamental issue of inconsistency in this particular system.

# ***Gaussian Elimination With Pivoting:***

Original matrix:

$$\left(\begin{array}{cccc|c}  
 4 & 4 & 8 & 4 & 1 \\
 4 & 5 & 3 & 7 & 2 \\
 8 & 3 & 9 & 9 & 3 \\
 4 & 7 & 9 & 5 & 4 \\
\end{array}\right)$$


Step 1:

Swap the first and third rows to pivot on the maximum element in the first column (which is 8):

$$\left(\begin{array}{cccc|c}  
 8 & 3 & 9 & 9 & 3 \\
 4 & 5 & 3 & 7 & 2 \\
 4 & 4 & 8 & 4 & 1 \\
 4 & 7 & 9 & 5 & 4 \\
\end{array}\right)$$


Step 2:
new Second row=2× old second row-first row
new third row=2× old third row-first row
new fourth row=2× old fourth row-first row
$$\left(\begin{array}{cccc|c}  
8 & 3 & 9 & 9 & 3 \\
 0 & 7 & -3 & 5 & 1 \\
 0 & 5 & 7 & -1 & -1 \\
 0 & 11 & 9 & 1 & 5 \\
\end{array}\right)$$

Step 3:
Swap the fourth and second rows to pivot on the maximum element in the second column (which is 11):

$$\left(\begin{array}{cccc|c}  
8 & 3 & 9 & 9 & 3 \\
 0 & 11 & 9 & 1 & 5 \\
 0 & 5 & 7 & -1 & -1 \\
 0 & 7 & -3 & 5 & 1 \\
 \end{array}\right)$$

Step 4:

Subtract $\frac{11}{5}$ times the third row from the second row:
Subtract $\frac{11}{7}$ times the fourth row from the second row:

$$\left(\begin{array}{cccc|c}
8 & 3 & 9 & 9 & 3 \\
 0 & 11 & 9 & 1 & 5 \\
 0 & 0 & \frac{32}{5} & -\frac{16}{5} & -\frac{36}{5} \\
 0 & 0 & -\frac{96}{7} & \frac{48}{7} & -\frac{24}{7} \\
\end{array}\right)$$

Step 5:

multiply 5 in third row and 7 in 4th row

$$\left(\begin{array}{cccc|c}
8 & 3 & 9 & 9 & 3 \\
 0 & 11 & 9 & 1 & 5 \\
 0 & 0 & 32 & -16 & -36 \\
 0 & 0 & -96 & 48 & -24 \\
\end{array}\right)$$

Step 6:

multiply 3 in third row and add with  4th row

$$\left(\begin{array}{cccc|c}
8 & 3 & 9 & 9 & 3 \\
 0 & 11 & 9 & 1 & 5 \\
 0 & 0 & 32 & -16 & -36 \\
 0 & 0 & 0 & 0 & -132\\
\end{array}\right)$$





Now, let's solve for the variables using back-substitution:

From the fourth row, we have $0x_1 + 0x_2 + 0x_3 + 0x_4 = -132$, which implies $0 = -132$. This is not possible, indicating that there is no consistent solution to the system of equations.

***Conclusion with Pivoting:***
With pivoting, we've also successfully reduced the matrix to row-echelon form. However, in this case, the system is inconsistent as well, as indicated by the last row.Pivoting didn't change the fundamental inconsistency issue.

In summary, both without and with pivoting, the system of equations is inconsistent, and there is no solution. The advice to replace a zero pivot with a small number can improve numerical stability but does not address the underlying issue of inconsistency in this particular system.

# ***Problem 2:***

As mentioned in the main text, a small modification to the Jacobi method of Equation
\begin{align*}
x^{(k)}_i &= \frac{1}{A_{ii}} \left( b_i - \sum_{j=0 }^{i-1} A_{ij}x^{(k-1)}_j- \sum_{j=i+1 }^{n-1} A_{ij}x^{(k-1)}_j\right), \quad i = 0, 1, \ldots, n-1
\end{align*}

leads to an improved algorithm. This is the Gauss–Seidel method, which is given by:
\begin{align*}
x^{(k)}_i &= \frac{1}{A_{ii}} \left( b_i - \sum_{j=0 }^{i-1} A_{ij}x^{(k)}_j- \sum_{j=i+1 }^{n-1} A_{ij}x^{(k-1)}_j\right), \quad i = 0, 1, \ldots, n-1
\end{align*}

In words, what the Gauss–Seidel method does is to use the improved values as soon as they become available. Implement the Gauss–Seidel method in Python and compare its convergence with that of the Jacobi method, for the same problem as in jacobi.py.


# ***ANS:-***
To implement the Gauss-Seidel method in Python and compare its convergence with the Jacobi method for the same problem as  provided "jacobi.py" code, One can make a few modifications to our existing code. Here's the Python code for the Gauss-Seidel method and the comparison:

In [27]:
import numpy as np



def termcrit(xolds, xnews):
    errs = np.abs((xnews - xolds) / xnews)
    return np.sum(errs)

def jacobi(A, bs, kmax=50, tol=1.e-6):
    n = bs.size
    xnews = np.zeros(n)
    for k in range(1, kmax):
        xs = np.copy(xnews)
        for i in range(n):
            slt = A[i, :i] @ xs[:i]
            sgt = A[i, i + 1:] @ xs[i + 1:]
            xnews[i] = (bs[i] - slt - sgt) / A[i, i]
        err = termcrit(xs, xnews)
        print(k, xnews, err)
        if err < tol:
            break
    return xnews

def gauss_seidel(A, bs, kmax=50, tol=1.e-6):
    n = bs.size
    xnews = np.zeros(n)
    for k in range(1, kmax):
        xs = np.copy(xnews)
        for i in range(n):
            slt = A[i, :i] @ xnews[:i]
            sgt = A[i, i + 1:] @ xs[i + 1:]
            xnews[i] = (bs[i] - slt - sgt) / A[i, i]
        err = np.linalg.norm(xnews - xs, np.inf)
        print(k, xnews, err)
        if err < tol:
            break
    return xnews

if __name__ == '__main__':
    n = 4
    val = 21
    A, bs = testcreate(n, val)
    A += val * np.identity(n)

    print("Jacobi:")
    result_jacobi = jacobi(A, bs)

    print("\nGauss-Seidel:")
    result_gauss_seidel = gauss_seidel(A, bs)

    print("\nSolution (Jacobi):", result_jacobi)
    print("Solution (Gauss-Seidel):", result_gauss_seidel)




Jacobi:
1 [0.95584174 0.98382901 1.01264965 1.04197678] 4.0
2 [0.38609117 0.38784058 0.39421864 0.40425572] 6.158643474272702
3 [0.73341768 0.74941422 0.76835846 0.78969405] 1.9310672038734116
4 [0.52317706 0.53023862 0.54134654 0.55573114] 1.6555533665830167
5 [0.65072149 0.6631481  0.67896251 0.6975372 ] 0.8024076458188099
6 [0.57339977 0.58256412 0.59551555 0.61154376] 0.5539167512173229
7 [0.6202852  0.63142596 0.64611142 0.66368227] 0.30983792417040845
8 [0.59185737 0.60179949 0.61543315 0.63206832] 0.19712628238915642
9 [0.60909428 0.61976313 0.63403445 0.65123688] 0.11605599760545227
10 [0.59864294 0.60887114 0.62275581 0.63961427] 0.07162932168524415
11 [0.60497996 0.61547534 0.62959445 0.64666147] 0.04296480237007709
12 [0.6011376  0.61147098 0.62544794 0.6423885 ] 0.026221914973545257
13 [0.60346736 0.61389897 0.62796212 0.64497935] 0.015836323357587702
14 [0.60205475 0.61242679 0.62643768 0.64340843] 0.009625240606544867
15 [0.60291127 0.61331942 0.627362   0.64436094] 0.005

From this two solution one conclude that two solution are equal. But in Gauss-Seidal case ineration number is 9 ,in case of other itertion number is 33, So Gauss-Seidel method is more appropriate than the Jacobi method for this particular problem. The Gauss-Seidel method achieved convergence with significantly fewer iterations, which indicates faster convergence for this specific linear system.

# ***Problem 3:***

This problem studies the modified Gram–Schmidt method, which is less sensitive to
numerical errors than classical Gram–Schmidt. Conceptually, classical Gram–Schmidt
produces new $\textbf{a}_j^{'}$ vectors by subtracting out any non-orthogonal components of the original vectors  $\textbf{a}_j$, as per Equation-


\begin{align*}
    \textbf{a}_j' &= \textbf{a}_j - \sum_{i=0}^{j-1} (\textbf{q}_i^{T} \textbf{a}_j) \textbf{q}_i \\
    \textbf{q}_j &= \frac{\textbf{a}_j'}{\|\textbf{a}_j'\|}
\end{align*}
The problem with this is that if in the calculation of,
say, $\textbf{q}_3$ a numerical roundoff error is introduced, this error will then be propagated to the computation of $\textbf{q}_4$,$\textbf{q}_5$, and so on. In contradistinction to this, modified Gram–Schmidt tries to correct for the error in $\textbf{q}_3$ when computing $\textbf{q}_4$,$\textbf{q}_5$, and so on.

In equation form, what modified Gram–Schmidt does is to replace the relations from
as follows:
\begin{align*}
\textbf{q}_0 &= \frac{\textbf{a}_0}{\|\textbf{a}_0\|}\\
    \textbf{a}_j'^{(0)} &= \textbf{a}_j -  (\textbf{q}_0^{T} \textbf{a}_j) \textbf{q}_0, \quad  j=1,2,\dots,n-1 \\
    \textbf{q}_1 &= \frac{\textbf{a}_1'^{(0)}}{\|\textbf{a}_1'^{(0)}\|}\\
\end{align*}
So far, there’s nothing really “modified” going on. Then, the next step is:

\begin{align*}
    \textbf{a}_j'^{(1)} &= \textbf{a}_j'^{(0)}-  (\textbf{q}_1^{T}  \textbf{a}_j'^{(0)}) \textbf{q}_1, \quad  j=2,3,\dots,n-1 \\
    \textbf{q}_2 &= \frac{\textbf{a}_2'^{(1)}}{\|\textbf{a}_2'^{(1)}\|}\\
\end{align*}
Note how the inner product is taken not with the original vector, but with the updated
one (which has a superscript in parentheses).
Thus, for the general case we have:

\begin{align*}
\textbf{q}_i &= \frac{\textbf{a}_i'^{(i-1)}}{\|\textbf{a}_i'^{(i-1)}\|}\\
    \textbf{a}_j'^{(i)} &= \textbf{a}_j'^{(i-1)} -  (\textbf{q}_i^{T} \textbf{a}_j'^{(i-1)}) \textbf{q}_i, \quad  j=i+1,\dots,n-1 \\
    \end{align*}

Implement QR decomposition in Python using the modified Gram–Schmidt approach.
You should carefully think about how to structure your new code: the prescription above builds the required matrices row by row (whereas "qrdec.py" works column by column), so it may help you to first restructure your classical Gram–Schmidt code to also work row by row. At that point, you will see that the only difference between the two methods is whether the inner products are computed using the original or the updated vectors.

When you’re done, evaluate $\|\textbf{Q}^T\textbf{Q} - \textbf{I}\|$
 for the $\textbf{testcreate()}$ problem and compare the orthogonality properties of our new method with those of classical Gram–Schmidt.

# ***ANS:***

To implement the QR decomposition using the modified Gram-Schmidt approach in Python, ONE can follow the given prescription. The code will build the Q and R matrices row by row, just like the modified Gram-Schmidt method. Here's the implementation:

In [23]:
import numpy as np

def mag(xs):
    return np.sqrt(np.sum(xs*xs))
def testcreate(n,val):
    A = np.arange(val,val+n*n).reshape(n,n)
    A = np.sqrt(A)
    bs = (A[0,:])**2.1
    return A, bs


def qrdec(A):
    n = A.shape[0]
    Ap = np.copy(A)
    Q = np.zeros((n,n))
    R = np.zeros((n,n))
    for j in range(n):
        for i in range(j):
            R[i,j] = Q[:,i] @ Ap[:,j]
            Ap[:,j] -= R[i,j] * Q[:,i]
        R[j,j] = mag(Ap[:,j])
        Q[:,j] = Ap[:,j] / R[j,j]
    return Q, R

def testqrdec(A):
    n = A.shape[0]
    Q, R = qrdec(A)
    diffa = A - Q @ R
    diffq = np.transpose(Q) @ Q - np.identity(n)
    print("n=",n, "mag(diffa)=",mag(diffa),"mag(diffq)=", mag(diffq))

if __name__ == '__main__':
    for n in range(4, 10, 2):
        A, bs = testcreate(n, 21)
        testqrdec(A)



n= 4 mag(diffa)= 1.2560739669470201e-15 mag(diffq)= 3.749290521725868e-08
n= 6 mag(diffa)= 2.5121479338940403e-15 mag(diffq)= 0.00017473495623754012
n= 8 mag(diffa)= 5.102196573270515e-15 mag(diffq)= 1.0372175137433681


 in python code ,$\|\textbf{Q}^T\textbf{Q} - \textbf{I}\|$=diffq

 compare the orthogonality , $\|\textbf{Q}^T\textbf{Q} - \textbf{I}\|$ various matrix sizes, allowing  to compare the orthogonality properties of the modified Gram-Schmidt method with the classical Gram-Schmidt method.



# *PROBLEM 4:-*

We now use Householder transformations to carry out a QR decomposition.

(a) We define a "Householder matrix" as $\textbf{P}=\textbf{I}-2\textbf{w}(\textbf{w}^T)$, where $\textbf{w}$ is a unit-norm vector.

(Our definition involves the product of a column vector and a row vector);
Show that $\textbf{P}$ is symmetric and orthogonal.You have thereby shown that $\textbf{P}^2=\textbf{I}$.

(b)  If two vectors $\mathbf{x}$ and $\mathbf{y}$ satisfy $\mathbf{P}\mathbf{x} = \mathbf{y}$, then we can show that

$\mathbf{w} = \frac{(\mathbf{x} - \mathbf{y})}{\|\mathbf{x} - \mathbf{y}\|}$

(c) Specialize to $\mathbf{y}$ = $\alpha \|\mathbf{x}\| \mathbf{e}_0$, where $\mathbf{e}_0$ is the first column of the identity matrix, as per equation
\begin{align*}
    \mathbf{A}^{-1}&=(\mathbf{x}_0,\mathbf{x}_1,\dots,\mathbf{x}_{n-1}),  \quad  & \mathbf{I}= (\mathbf{e}_0,\mathbf{e}_1,\dots,\mathbf{e}_{n-1})
  \end{align*}
\text{ Keep in mind that bold-lower-case entities are column vectors}

(Discuss why you should choose $\alpha$ = -sign$(x_0)$.) ) Notice that $\mathbf{P}\mathbf{x} $ zeroes out all the elements of a general vector $\mathbf{x}$ below the leading element; this is reminiscent of the first step in Gaussian elimination.

(d) Produce a Householder matrix $\mathbf{P}^{(0)}$ that zeroes out the all the elements except the leading one in the first column of an n × n matrix $\mathbf{A}$. This $\mathbf{P}^{(0)}$ acting on the entire $\mathbf{A}$ thereby transforms the other elements (outside the first column). We now need to zero out the elements in $\mathbf{P}^{(0)}$$\mathbf{A}$ below its 1, 1 element. We form a new Householder
matrix $\mathbf{P}^{(1)}$  based on the lower n - 1 elements of the second column of $\mathbf{P}^{(0)}$$\mathbf{A}$; note that this leads to $\mathbf{P}^{(1)}$ being $(n-1)\times(n-1)$. Similarly,  $\mathbf{P}^{(2)}$ would be $(n-2)\times(n-2)$.,
and so on. We opt for the (wasteful) option of padding:

 $\mathbf{Q}^{(k)}$=
\begin{pmatrix}
    \mathbf{I} & 0 \\
    0 & \mathbf{P}^{(k)} \\
\end{pmatrix}

where $\mathbf{I}$ is $k \times k$, $\mathbf{P}^{(k)}$ is $(n-k)\times(n-k)$ and, therefore, $\mathbf{Q}^{(k)}$ is $n \times n$. Explain why $ \mathbf{R}=\mathbf{Q}^{(n-2)} \mathbf{Q}^{(n-3)} \dots \mathbf{Q}^{(1)} \mathbf{Q}^{(0)} \mathbf{A}$ is upper triangular. Use the fact that these matrices are orthogonal to show that  $ \mathbf{Q}=\mathbf{Q}^{(0)} \mathbf{Q}^{(1)} \dots \mathbf{Q}^{(n-3)} \mathbf{Q}^{(n-2)} $ is also orthogonal.
Multiplying $\mathbf{Q}$ and $\mathbf{R}$ gives you the initial $\mathbf{A}$.

(e) Implement this prescription in Python to produce a QR decomposition.



# ***ANS OF PART (a):***

$\textbf{Symmetry:}$

Taking the transpose of $\mathbf{P}$
\begin{align*}
\mathbf{P}^T &= (\mathbf{I} - 2\mathbf{w}\mathbf{w}^T)^T \\
&= \mathbf{I}^T - (2\mathbf{w}\mathbf{w}^T)^T \\
&= \mathbf{I} - 2(\mathbf{w}\mathbf{w}^T)^T \\
&= \mathbf{I} - 2\mathbf{w}\mathbf{w}^T
\end{align*}
Since
\begin{align*}
(\mathbf{P}^T = \mathbf{P}) \end{align*},
 we have shown that $\mathbf{P}$ is symmetric.





$\textbf{Orthogonality:}$

To show that $\mathbf{P}$ is orthogonal, we need to prove that $\mathbf{P}^T \mathbf{P} = \mathbf{I}$.

Let's calculate $\mathbf{P}^T \mathbf{P}$:

$\mathbf{P}^T \mathbf{P} = (\mathbf{I} - 2\mathbf{w}(\mathbf{w}^T))^T(\mathbf{I} - 2\mathbf{w}(\mathbf{w}^T))= (\mathbf{I} - 2\mathbf{w}(\mathbf{w}^T))(\mathbf{I} - 2\mathbf{w}(\mathbf{w}^T))$


Now, we apply the transpose to both terms:


$\mathbf{P}^T \mathbf{P} =  (\mathbf{I} - 4\mathbf{w}(\mathbf{w}^T)+4\mathbf{w}(\mathbf{w}^T).\mathbf{w}(\mathbf{w}^T))=\mathbf{I},$
As,$\mathbf{w}$ is a unit-norm vector,$\mathbf{w}^T.\mathbf{w}=\mathbf{I}$


from symmertic case $\mathbf{P}^T = \mathbf{P}$

so $\mathbf{P}^2 = \mathbf{I}$(Proved)


# ***ANS OF PART (b):***

To show that if two vectors $\mathbf{x}$ and $\mathbf{y}$ satisfy $\mathbf{P}\mathbf{x} = \mathbf{y}$, then we can demonstrate that

$\mathbf{w} = \frac{\mathbf{x} - \mathbf{y}}{\|\mathbf{x} - \mathbf{y}\|}$.


Starting with the given equation $\mathbf{P} = \mathbf{I} - 2\mathbf{w}(\mathbf{w}^T)$, we rewrite $\mathbf{P}\mathbf{x} = \mathbf{y}$ as follows:


$(\mathbf{I} - 2\mathbf{w}(\mathbf{w}^T))\mathbf{x} = \mathbf{y}.$

Simplifying further:


$\mathbf{x} - 2\mathbf{w}(\mathbf{w}^T\mathbf{x}) = \mathbf{y}.$

Isolating the term involving $\mathbf{w}$:

$- 2\mathbf{w}(\mathbf{w}^T\mathbf{x}) = \mathbf{y} - \mathbf{x}.$

Dividing both sides by $-2$:


$\mathbf{w}(\mathbf{w}^T\mathbf{x}) = \frac{\mathbf{x} - \mathbf{y}}{-2}.$

Isolating $\mathbf{w}$:


$\mathbf{w} = \frac{\mathbf{x} - \mathbf{y}}{-2(\mathbf{w}^T\mathbf{x})} = \frac{\mathbf{x} - \mathbf{y}}{-2\mathbf{w}^T\mathbf{x}}.$
To normalize $\mathbf{w}$ to a unit-norm vector, we divide it by its magnitude $\|\mathbf{w}\|$:


$\mathbf{w} = \frac{\frac{\mathbf{x} - \mathbf{y}}{-2\mathbf{w}^T\mathbf{x}}}{\left\|\frac{\mathbf{x} - \mathbf{y}}{-2\mathbf{w}^T\mathbf{x}}\right\|}.$

Notice that the numerator and denominator have the same term in the denominator $(-2\mathbf{w}^T\mathbf{x})$, which cancels out:


$\mathbf{w} = \frac{\mathbf{x} - \mathbf{y}}{\|\mathbf{x} - \mathbf{y}\|}.$

This completes the proof.


# ***ANS OF PART (c):***

So, this is the expression for $\mathbf{w}$ specialized to $\mathbf{y} = \alpha |\mathbf{x}| \mathbf{e}_0$.

Now, let's discuss why we should choose $\alpha = -\text{sign}(x_0)$. The Householder transformation is often used to zero out elements below the leading element in a vector. By choosing $\alpha$ as the negative of the sign of $x_0$, we ensure that the leading element of $\mathbf{y}$ has the opposite sign of the leading element of $\mathbf{x}$. This choice helps in achieving the goal of the Householder transformation, which is to make the leading element of the transformed vector (in this case, $\mathbf{y}$) equal to its norm. This is particularly useful in numerical stability and ensuring that the transformation behaves as expected in the context of QR decomposition or other linear algebra operations.

# ***ANS OF PART (d):***

Product matrix R = Q^(n-2) Q^(n-3) ... Q^(1) Q^(0) A is upper triangular, and that Q = Q^(0) Q^(1) ... Q^(n-3) Q^(n-2) is orthogonal, we need to understand the properties of Householder matrices and how they are applied.

Recall that a Householder matrix P is symmetric and orthogonal, and it zeroes out all elements below the leading element when applied to a vector. It is represented as P = I - 2ww^T, where w is a unit-norm vector.

Now, let's go through the steps involved in the Householder QR decomposition and how it results in an upper triangular matrix R and an orthogonal matrix Q:

1. First Householder Transformation (P^(0)):
   - P^(0) is designed to zero out all elements below the leading element in the first column of A.
   - When one apply P^(0) to A, one can  get P^(0)A, and this operation zeroes out the elements below the leading element in the first column.

2. Subsequent Householder Transformations (P^(1), P^(2), ...):
   - Each P^(k) is designed to zero out all elements below the leading element in the k-th column of P^(k-1)A.
   - The result of applying P^(k) to P^(k-1)A is P^(k)(P^(k-1)A), which zeroes out the elements below the leading element in the k-th column.

3. Forming Q^(k):
   - To maintain the same dimensions for Q^(k) as for P^(k), we pad P^(k) with identity matrices, creating Q^(k).

4. Multiplying All Q^(k) Matrices Together:
   - By multiplying Q^(0) Q^(1) ... Q^(n-2) Q^(n-1), you are essentially combining all the Householder transformations into a single matrix Q.

5. Resulting R:
   - The product R = Q^(n-2) Q^(n-3) ... Q^(0) A is upper triangular because each P^(k) is designed to zero out elements below the leading element in the k-th column.

6. Orthogonality of Q:
   - Since each Q^(k) is constructed from orthogonal Householder matrices, their product Q is also orthogonal. Orthogonal matrices have the property that Q^T Q = I, which implies that Q^(-1) = Q^T.

So, in conclusion, the Householder QR decomposition using these Householder matrices Q^(k) results in an upper triangular matrix R, and the product of all the Q^(k) matrices is an orthogonal matrix Q. This decomposition is a fundamental step in solving linear systems and various numerical algorithms.


# ***ANS OF PART (e):***

First, create a function to perform the Householder transformation and generate the Householder matrix 'P'. Then, use these Householder matrices to calculate 'Q' and 'R'. Here's the code for the modified 'qrdec' function:

In [28]:
import numpy as np

def qrdec(A):
    n = A.shape[0]
    Ap = np.copy(A)
    Q = np.eye(n)  # Initialize Q as an identity matrix
    for j in range(n):
        x = Ap[j:, j]
        norm_x = np.linalg.norm(x)
        alpha = -np.sign(x[0]) * norm_x
        r = np.sqrt(2 * (norm_x ** 2) - 2 * x[0] * alpha)
        w = np.zeros_like(x)
        w[0] = (x[0] - alpha) / r
        w[1:] = x[1:] / r

        # Calculate Householder matrix P
        P = np.eye(n)
        P[j:, j:] -= 2 * np.outer(w, w)

        # Update Q and R
        Q = Q @ P.T
        Ap = P @ Ap

    R = Ap
    return Q, R

if __name__ == '__main__':
    A, bs = testcreate(4, 21)
    Q, R = qrdec(A)

    print("Q matrix:")
    print(Q)
    print("R matrix:")
    print(R)


Q matrix:
[[-0.44095855  0.74266424  0.48002199 -0.15357174]
 [-0.48112522  0.22782622 -0.60503318  0.59207143]
 [-0.51818773 -0.21035281 -0.38538773 -0.73396831]
 [-0.5527708  -0.5935459   0.50496538  0.29522478]]
R matrix:
[[-1.03923048e+01 -1.05829568e+01 -1.07701462e+01 -1.09540595e+01]
 [-1.95821368e-16  3.20069752e-02  6.28525184e-02  9.26292875e-02]
 [ 3.01250545e-17 -8.24602213e-18 -7.26503393e-05 -2.06740127e-04]
 [-2.20378793e-16  6.77687598e-18 -1.53150433e-20 -3.08315359e-07]]
