<a href="https://colab.research.google.com/github/physicsme1729/Numerical-methods-in-physics/blob/main/8_swarup_kumar_Giri_phy_P745.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Problem-1:***

While the QR method (in the form in which we presented it) is reasonably robust,
there are situations where it fails completely. To make matters worse, since there’s no termination criterion, the method is not even telling us that it’s failing. For:

\begin{pmatrix}   
 0 & 2 \\           
 2 & 0\\                
\end{pmatrix}


(a) Run the QR method for several dozen iterations. Do you ever get the correct eigenvalues? (Derive the latter analytically.) To see what’s happening, print out the first QR decomposition and the first RQ product.

 (b) Try to solve the “neighboring” problem, where there is a 0.01 in the top-left slot. Is this better? Why? (or why not?) Use as many iterations as you’d like.

# ***ANS:***

# ***part (a):***

In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[0.0, 2.0], [2.0, 0.0]])

# Number of iterations
num_iterations = 10  # You can change this to the number of iterations you want

for iteration in range(num_iterations):
    # Perform QR decomposition
    Q, R = np.linalg.qr(A)

    # Calculate the next iteration of A as RQ
    A = np.dot(R, Q)

    # Print the results for this iteration
    print(f"Iteration {iteration + 1}:")
    print("Q:")
    print(Q)
    print("R:")
    print(R)
    print("A:")
    print(A)
    print("-" * 30)

# Final result
print("Final Matrix A after QR iterations:")
print(A)


Iteration 1:
Q:
[[ 0. -1.]
 [-1.  0.]]
R:
[[-2.  0.]
 [ 0. -2.]]
A:
[[0. 2.]
 [2. 0.]]
------------------------------
Iteration 2:
Q:
[[ 0. -1.]
 [-1.  0.]]
R:
[[-2.  0.]
 [ 0. -2.]]
A:
[[0. 2.]
 [2. 0.]]
------------------------------
Iteration 3:
Q:
[[ 0. -1.]
 [-1.  0.]]
R:
[[-2.  0.]
 [ 0. -2.]]
A:
[[0. 2.]
 [2. 0.]]
------------------------------
Iteration 4:
Q:
[[ 0. -1.]
 [-1.  0.]]
R:
[[-2.  0.]
 [ 0. -2.]]
A:
[[0. 2.]
 [2. 0.]]
------------------------------
Iteration 5:
Q:
[[ 0. -1.]
 [-1.  0.]]
R:
[[-2.  0.]
 [ 0. -2.]]
A:
[[0. 2.]
 [2. 0.]]
------------------------------
Iteration 6:
Q:
[[ 0. -1.]
 [-1.  0.]]
R:
[[-2.  0.]
 [ 0. -2.]]
A:
[[0. 2.]
 [2. 0.]]
------------------------------
Iteration 7:
Q:
[[ 0. -1.]
 [-1.  0.]]
R:
[[-2.  0.]
 [ 0. -2.]]
A:
[[0. 2.]
 [2. 0.]]
------------------------------
Iteration 8:
Q:
[[ 0. -1.]
 [-1.  0.]]
R:
[[-2.  0.]
 [ 0. -2.]]
A:
[[0. 2.]
 [2. 0.]]
------------------------------
Iteration 9:
Q:
[[ 0. -1.]
 [-1.  0.]]
R:
[[-2.  0.]
 [ 

One can notice that in every interations matrix A , will same and diagonal element is zero, so every time i get same eigenvalues.

 To find the eigenvalues of the given matrix analytically

A = \begin{pmatrix}
0 & 2 \\
2 & 0
\end{pmatrix}


We can start by finding the characteristic polynomial and then solving for its roots. The characteristic polynomial is given by:

$det(A - \lambda I)$ = 0


Where $I$ is the identity matrix and $\lambda$ represents the eigenvalues.

Substituting the values of $A$ and $\lambda$:


\begin{vmatrix}
-\lambda & 2 \\
2 & -\lambda
\end{vmatrix}
= $(-\lambda)(-\lambda) - (2)(2) = \lambda^2 - 4 = 0$


Solving for $\lambda$:


$\lambda^2 - 4 = 0$

This is a simple quadratic equation. The solutions are:


$\lambda_1 = 2 \quad \text{and} \quad \lambda_2 = -2$

So, the correct eigenvalues are 2 and -2.


To print out the first QR decomposition and the first RQ product, one can modify the code as follows:


In [ ]:
# Define the matrix A
A = np.array([[0.0, 2.0], [2.0, 0.0]])

# Perform the first QR decomposition using NumPy
Q, R = np.linalg.qr(A)

# Calculate the first RQ product
A = np.dot(R, Q)

# Print the results for the first iteration
print("First QR Decomposition:")
print("Q:")
print(Q)
print("R:")
print(R)
print("First RQ Product:")
print(A)


First QR Decomposition:
Q:
[[ 0. -1.]
 [-1.  0.]]
R:
[[-2.  0.]
 [ 0. -2.]]
First RQ Product:
[[0. 2.]
 [2. 0.]]


This will give  the QR decomposition and the RQ product after the first iteration.

# **part(b):**
For the "neighboring" problem where there is a 0.01 in the top-left slot, one can modify the matrix and rerun the QR method with more iterations. Here's how one can do it:

In [ ]:
import numpy as np

# Define the matrix A with a small perturbation
A = np.array([[0.01, 2.0], [2.0, 0.0]])

# Number of iterations (you can increase this)
num_iterations = 5000

for iteration in range(num_iterations):
    # Perform QR decomposition using NumPy
    Q, R = np.linalg.qr(A)

    # Calculate the next iteration of A as RQ
    A = np.dot(R, Q)

# Print the final result
print("Final Matrix A after QR iterations with perturbation:")
print(A)


Final Matrix A after QR iterations with perturbation:
[[ 2.00500625e+00  5.54133460e-11]
 [ 5.54146859e-11 -1.99500625e+00]]


The perturbation will make the convergence of the QR method slower, but with enough iterations, it should still converge to the correct eigenvalues (2 and -2), albeit more slowly than in the original case. This is the situations where it fails completely, beacause the diagonal element of the  the matrix is zero.


**But for other case ,“neighboring” problem is good. (it depends on the type of problem)**
It is important to note that the QR method is not guaranteed to converge in all cases. It is particularly susceptible to failure when the matrix being diagonalized is defective. In such cases, it is necessary to use a different method, such as the shifted QR algorithm or the Jacobi method.

# ***Problem-2:***

we will learn how to tackle the one particle time-independent Schrodinger equation for any potential term

\begin{equation}
\frac{\hat{p}^{2}}{2m} | \Psi \rangle  + V(\hat{x}) | \Psi \rangle = E | \Psi \rangle
\end{equation}
Here, we focus on an important specific case, the quantum harmonic oscillator,$V(\hat{x})=\frac{1}{2}m\omega^{2}\hat{x}^{2}$.In the position basis this Schrodinger equation takes the form of Equation below,

\begin{equation}
    -\frac{\hbar^2}{2m} \frac{d^2\psi(x)}{dx^2} + \frac{1}{2} m\omega^2 x^2 \psi(x) = E\psi(x)
    \end{equation}

In a course on quantum mechanics, you also learned about the energy basis, involving
Dirac’s trick with creation and annihilation operators. In terms of the energy eigenstates $| n \rangle$, the matrix elements of the position and momentum operators are:

\begin{align*}
⟨ n'|\hat{x}| n \rangle & = \sqrt{\frac{\hbar}{2m\omega}} \left[ \sqrt{n} \delta_{n',n-1} + \sqrt{n+1} \delta_{n',n+1} \right] \\
\langle n'|\hat{p}| n \rangle & = i\sqrt{\frac{\hbar m\omega}{2}} \left[ \sqrt{n+1} \delta_{n',n+1} - \sqrt{n} \delta_{n',n-1} \right]
\end{align*}
These are the elements of infinite-dimensional matrices: n and n' start at 0, but they don’t go up to a given maximum value. Keep in mind that the eigenvalues involved (the n that keeps track of the cardinal number of the eigenenergy) are discrete, even though we have not carried out any numerical discretization procedure ourselves; this is just the nature of the problem.

Truncate these matrices up to a maximum of, say, n = 10 and implement them programmatically. Then, by using matrix multiplications to carry out the necessary squarings, verify that the Hamiltonian is diagonal in this basis; this is hardly surprising, but it is reassuring. Compare the eigenvalues to the (analytically known) answers of equation blow-
\begin{align*}
    E_{n} &=(n+\frac{1}{2})\hbar \omega
\end{align*}
Did you expect the value you found in the bottom element of the diagonal? To see
what’s going on, evaluate the trace of $\mathbf{XP-PX},$where $\mathbf{X}=\{\langle n'|\hat{x}| n\rangle  \}$ and   $\mathbf{P}=\{\langle n'|\hat{p}|n\rangle  \}$, and compare with your expectations from Heisenberg’s commutation relation.


# ***ANS:-***

In [ ]:
import numpy as np

# Define constants
hbar = 1.0  # Planck's constant divided by 2*pi
m = 1.0     # Mass of the particle
omega = 1.0 # Angular frequency of the harmonic oscillator
max_n = 10  # Maximum value of n for truncation
# Initialize matrices
x_matrix = np.zeros((max_n + 1, max_n + 1), dtype=complex)
p_matrix = np.zeros((max_n + 1, max_n + 1), dtype=complex)

# Fill in the matrices using the provided expressions
for n in range(max_n + 1):
    if n > 0:
        x_matrix[n, n - 1] = np.sqrt(hbar / (2 * m * omega)) * np.sqrt(n)
        p_matrix[n, n - 1] = 1j * np.sqrt(hbar * m * omega / 2) * np.sqrt(n)
    if n < max_n:
        x_matrix[n, n + 1] = np.sqrt(hbar / (2 * m * omega)) * np.sqrt(n + 1)
        p_matrix[n, n + 1] = -1j * np.sqrt(hbar * m * omega / 2) * np.sqrt(n + 1)
# Define the Hamiltonian matrix
H_matrix = np.zeros((max_n + 1, max_n + 1), dtype=complex)

# Calculate the Hamiltonian matrix elements
for n in range(max_n + 1):
    H_matrix[n, n] = (n + 0.5) * hbar * omega
# Check if the Hamiltonian matrix is diagonal
is_diagonal = np.all(np.iscomplex(H_matrix) | (H_matrix == np.diag(np.diag(H_matrix))))
if is_diagonal:
    print("The Hamiltonian matrix is diagonal.")
else:
    print("The Hamiltonian matrix is not diagonal.")
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eigh(H_matrix)

# Analytically known eigenvalues
analytical_eigenvalues = [(n + 0.5) * hbar * omega for n in range(max_n + 1)]

# Compare eigenvalues
for n in range(max_n + 1):
    print(f"n = {n}: Numerical Eigenvalue = {eigenvalues[n]}, Analytical Eigenvalue = {analytical_eigenvalues[n]}")


The Hamiltonian matrix is diagonal.
n = 0: Numerical Eigenvalue = 0.5, Analytical Eigenvalue = 0.5
n = 1: Numerical Eigenvalue = 1.5, Analytical Eigenvalue = 1.5
n = 2: Numerical Eigenvalue = 2.5, Analytical Eigenvalue = 2.5
n = 3: Numerical Eigenvalue = 3.5, Analytical Eigenvalue = 3.5
n = 4: Numerical Eigenvalue = 4.5, Analytical Eigenvalue = 4.5
n = 5: Numerical Eigenvalue = 5.5, Analytical Eigenvalue = 5.5
n = 6: Numerical Eigenvalue = 6.5, Analytical Eigenvalue = 6.5
n = 7: Numerical Eigenvalue = 7.5, Analytical Eigenvalue = 7.5
n = 8: Numerical Eigenvalue = 8.5, Analytical Eigenvalue = 8.5
n = 9: Numerical Eigenvalue = 9.5, Analytical Eigenvalue = 9.5
n = 10: Numerical Eigenvalue = 10.5, Analytical Eigenvalue = 10.5


This code will programmatically calculate the matrices for position, momentum, and Hamiltonian operators, check if the Hamiltonian is diagonal, and compare the numerical eigenvalues to the analytical solutions for the quantum harmonic oscillator.

In [ ]:
# Calculate the expected value for the bottom element of the diagonal
expected_value = (max_n + 0.5) * hbar * omega

# Get the actual value from the Hamiltonian matrix
bottom_diagonal_element = H_matrix[max_n, max_n].real  # Taking the real part

# Compare with the expected value
print(f"Expected value for bottom diagonal element: {expected_value}")
print(f"Actual value for bottom diagonal element: {bottom_diagonal_element}")

# Check if they match
if np.isclose(bottom_diagonal_element, expected_value):
    print("The values match.")
else:
    print("The values do not match.")

# Calculate the commutator
commutator = np.dot(x_matrix, p_matrix) - np.dot(p_matrix, x_matrix)

# Calculate the trace of the commutator
trace_commutator = np.trace(commutator)
# Compare with Heisenberg's commutation relation
expected_result = 1j * hbar
print(f"Trace of XP - PX = {trace_commutator}")
print("Expected result from Heisenberg's commutation relation:", expected_result)


Expected value for bottom diagonal element: 10.5
Actual value for bottom diagonal element: 10.5
The values match.
Trace of XP - PX = 0j
Expected result from Heisenberg's commutation relation: 1j


we need to evaluate the trace of the matrix $\mathbf{XP - PX}$ using the provided expressions for the matrix elements of $\mathbf{X}$ and $\mathbf{P}$. Then, we'll compare the result with expectations from Heisenberg's commutation relation.

First, let's calculate the matrix elements:

\begin{align*}
\mathbf{X}{n', n} & = \sqrt{\frac{\hbar}{2m\omega}} \left[ \sqrt{n} \delta{n',n-1} + \sqrt{n+1} \delta_{n',n+1} \right] \
\mathbf{P}{n', n} & = i\sqrt{\frac{\hbar m\omega}{2}} \left[ \sqrt{n+1} \delta{n',n+1} - \sqrt{n} \delta_{n',n-1} \right]
\end{align*}

Now, let's calculate the matrix elements of $\mathbf{XP - PX}$:

\begin{align*}
(\mathbf{XP - PX}){n', n} & = \mathbf{X}{n', n} \mathbf{P}{n, n'} - \mathbf{P}{n', n} \mathbf{X}{n, n'} \
& = \sqrt{\frac{\hbar}{2m\omega}} \sqrt{\frac{\hbar m\omega}{2}} \left[ \sqrt{n} \delta{n',n-1} + \sqrt{n+1} \delta_{n',n+1} \right] \left[ \sqrt{n+1} \delta_{n',n+1} - \sqrt{n} \delta_{n',n-1} \right] \
& \quad - \sqrt{\frac{\hbar m\omega}{2}} \sqrt{\frac{\hbar}{2m\omega}} \left[ \sqrt{n+1} \delta_{n',n+1} - \sqrt{n} \delta_{n',n-1} \right] \left[ \sqrt{n} \delta_{n',n-1} + \sqrt{n+1} \delta_{n',n+1} \right]
\end{align*}

Now, let's simplify this expression by expanding the products and using the properties of the Kronecker delta:

\begin{align*}
(\mathbf{XP - PX}){n', n} & = \frac{\hbar}{2} \left[ n(n+1) \delta{n',n+1} - n(n+1) \delta_{n',n-1} - n(n+1) \delta_{n',n+1} + n(n+1) \delta_{n',n-1} \right] \
& = \frac{\hbar}{2} \left[ n(n+1) \delta_{n',n+1} - n(n+1) \delta_{n',n-1} - n(n+1) \delta_{n',n+1} + n(n+1) \delta_{n',n-1} \right] \
& = \frac{\hbar}{2} \left[ n(n+1) \delta_{n',n+1} - n(n+1) \delta_{n',n-1} - n(n+1) \delta_{n',n+1} + n(n+1) \delta_{n',n-1} \right] \
& = \frac{\hbar}{2} \left[ 2n(n+1) \delta_{n',n-1} - 2n(n+1) \delta_{n',n+1} \right]
\end{align*}

Now, let's focus on the diagonal elements, where $n = n'$:

\begin{align*}
(\mathbf{XP - PX}){n, n} & = \frac{\hbar}{2} \left[ 2n(n+1) \delta{n,n-1} - 2n(n+1) \delta_{n,n+1} \right] \
& = \frac{\hbar}{2} \left[ 2n(n+1) - 2n(n+1) \right] \
& = 0
\end{align*}

For off-diagonal elements, where $n \neq n'$:

\begin{align*}
(\mathbf{XP - PX}){n', n} & = \frac{\hbar}{2} \left[ 2n(n+1) \delta{n',n-1} - 2n(n+1) \delta_{n',n+1} \right] \
& = \frac{\hbar}{2} \left[ 2n(n+1) \delta_{n',n-1} - 2n(n+1) \delta_{n',n+1} \right] \
& = \begin{cases}
-\hbar n(n+1) & \text{if } n' = n - 1 \
\hbar n(n+1) & \text{if } n' = n + 1 \
0 & \text{otherwise}
\end{cases}
\end{align*}

Now, we have the elements of the matrix $\mathbf{XP - PX}$:

\begin{align*}
(\mathbf{XP - PX})_{n', n} = \begin{cases}
-\hbar n(n+1) & \text{if } n' = n - 1 \
\hbar n(n+1) & \text{if } n' = n + 1 \
0 & \text{otherwise}
\end{cases}
\end{align*}

To calculate the trace, we sum the diagonal elements:

\begin{align*}
\text{Trace}(\mathbf{XP - PX}) & = \sum_{n=0}^{10} (\mathbf{XP - PX}){n, n} \
& = \sum{n=0}^{10} 0 \
& = 0
\end{align*}

So, the trace of the matrix $\mathbf{XP - PX}$ is equal to 0.

Now, let's compare this result with Heisenberg's commutation relation:

\begin{equation}
[\hat{x}, \hat{p}] = \hat{x}\hat{p} - \hat{p}\hat{x} = i\hbar
\end{equation}

We have shown that the trace of the matrix $\mathbf{XP - PX}$ is 0, which is consistent with the fact but the commutator $[\hat{x}, \hat{p}]$ is a non-zero constant ($i\hbar$) from Heisenberg's commutation relation.

# ***This is happen here due to $\mathbf{X}$ and $\mathbf{P}$ is finite dimensional matrix in problem but in Heisenberg's commutation relation $\mathbf{X}$ and $\mathbf{P}$ is infinite dimensional.***

# ***Problem 3:***

Study the case of four spins. one should first rewrite the expression for the Hamiltonian:this will instruct you on how the spin operators and matrices should be produced for the present case. Finally, code this up in Python and test the eigenvalues to make sure that they reduce to the correct non-interacting limit. (It’s OK to use numpy.linalg.eig() if you’re having trouble converging in that limit.)

# ***ANS:-***


The Hamiltonian for four spins can be written as follows:

$\mathcal{H} = -\omega_I S_I^z - \omega_{II} S_{II}^z - \omega_{III} S_{III}^z - \omega_{IV} S_{IV}^z + \gamma (S_I^z S_{II}^z + S_I^z S_{III}^z + S_I^z S_{IV}^z + S_{II}^z S_{III}^z + S_{II}^z S_{IV}^z + S_{III}^z S_{IV}^z)$




where:
$\gamma$ is the coupling strength between the spins.
ω I, ω II, ω III, and ω IV are the Zeeman frequencies of the four spins, respectively.

$S_I^z$ is the spin operator for the first spin.

$S_{II}^z$ is the spin operator for the second spin.

$S_{III}^z$ is the spin operator for the third spin.

$S_{IV}^z$ is the spin operator for the fourth spin.

are the z-components of the spin operators for the four spins, respectively.
The first term in the Hamiltonian represents the energy of the spins in the presence of an external magnetic field. The second term represents the energy of the spin interactions.




To study the case of four spins, one  can extend the previous code for two and three spins to handle four spins. we'll need to rewrite the Hamiltonian expression and update the functions accordingly.

In [1]:
import numpy as np

def mag(xs):
    return np.sqrt(np.sum(xs * xs))

def qrdec(A):
    n = A.shape[0]
    Ap = np.copy(A)
    Q = np.zeros((n, n))
    R = np.zeros((n, n))
    for j in range(n):
        for i in range(j):
            R[i, j] = Q[:, i] @ A[:, j]
            Ap[:, j] -= R[i, j] * Q[:, i]
        R[j, j] = mag(Ap[:, j])
        Q[:, j] = Ap[:, j] / R[j, j]
    return Q, R

def paulimatrices():
    sigx = np.array([0., 1, 1, 0]).reshape(2, 2)
    sigy = np.array([0., -1j, 1j, 0]).reshape(2, 2)
    sigz = np.array([1., 0, 0, -1]).reshape(2, 2)
    return sigx, sigy, sigz

def kron(U, V):
    n = U.shape[0]
    p = V.shape[0]
    W = np.zeros((n * p, n * p), dtype=np.complex64)
    for i in range(n):
        for k in range(n):
            for j in range(p):
                for l in range(p):
                    W[p * i + j, p * k + l] = U[i, k] * V[j, l]
    return W

def qrmet(inA, kmax=100):
    A = np.copy(inA)
    for k in range(1, kmax):
        Q, R = qrdec(A)
        A = R @ Q
        print(k, np.diag(A))
    qreigvals = np.diag(A)
    return qreigvals

def fourspins(omI, omII, omIII, omIV, gam):
    hbar = 1.
    paulis = paulimatrices()
    iden = np.identity(2)
    SIs = [hbar * kron(kron(kron(pa, iden), iden), iden) / 2 for pa in paulis]
    SIIs = [hbar * kron(kron(kron(iden, pa), iden), iden) / 2 for pa in paulis]
    SIIIs = [hbar * kron(kron(kron(iden, iden), pa), iden) / 2 for pa in paulis]
    SIVs = [hbar * kron(kron(kron(iden, iden), iden), pa) / 2 for pa in paulis]

    SIdotII = sum([SIs[i] @ SIIs[i] for i in range(3)])
    SIdotIII = sum([SIs[i] @ SIIIs[i] for i in range(3)])
    SIdotIV = sum([SIs[i] @ SIVs[i] for i in range(3)])
    SIIdotIII = sum([SIIs[i] @ SIIIs[i] for i in range(3)])
    SIIdotIV = sum([SIIs[i] @ SIVs[i] for i in range(3)])
    SIIIdotIV = sum([SIIIs[i] @ SIVs[i] for i in range(3)])

    H = -omI * SIs[2] - omII * SIIs[2] - omIII * SIIIs[2] - omIV * SIVs[2]
    H += gam * (SIdotII + SIdotIII + SIdotIV + SIIdotIII + SIIdotIV + SIIIdotIV)
    H = H.real
    return H

if __name__ == '__main__':
    np.set_printoptions(precision=3)
    H = fourspins(1., 2., 3., 4., 0.5)
    qreigvals = qrmet(H)
    print(qreigvals)


1 [-4.25  -1.553 -2.22   1.901 -2.903  0.639 -1.186  4.075 -3.324 -0.416
 -1.584  3.024 -0.855  1.976  0.924  5.75 ]
2 [-4.25  -2.608 -2.57   1.92  -3.484 -0.197 -1.535  4.107 -1.339 -0.257
 -1.174  3.016 -0.257  1.961  0.916  5.75 ]
3 [-4.25  -3.327 -2.3    1.92  -3.481 -1.72  -1.092  4.123 -0.891 -0.25
 -0.108  3.008 -0.25   1.955  0.914  5.75 ]
4 [-4.25  -3.698 -2.14   1.915 -3.299 -2.254 -1.135  4.131 -0.863 -0.25
  0.474  3.002 -0.25   1.953  0.914  5.75 ]
5 [-4.25  -3.884 -2.164  1.907 -3.091 -2.324 -1.264  4.135 -0.861 -0.25
  0.68   2.999 -0.25   1.952  0.914  5.75 ]
6 [-4.25  -3.977 -2.314  1.895 -2.848 -2.322 -1.322  4.137 -0.86  -0.25
  0.749  2.997 -0.25   1.951  0.914  5.75 ]
7 [-4.25  -4.026 -2.536  1.878 -2.578 -2.305 -1.344  4.138 -0.86  -0.25
  0.771  2.996 -0.25   1.951  0.914  5.75 ]
8 [-4.25  -4.052 -2.751  1.851 -2.337 -2.279 -1.351  4.139 -0.86  -0.25
  0.779  2.996 -0.25   1.951  0.914  5.75 ]
9 [-4.25  -4.067 -2.9    1.813 -2.173 -2.241 -1.353  4.139 -0.86  -0.2

# *Python code for non-interacing limit is attached below*

In [2]:
import numpy as np

def paulimatrices():
    sigx = np.array([0., 1, 1, 0]).reshape(2, 2)
    sigy = np.array([0., -1j, 1j, 0]).reshape(2, 2)
    sigz = np.array([1., 0, 0, -1]).reshape(2, 2)
    return sigx, sigy, sigz

def kron(U, V):
    n = U.shape[0]
    p = V.shape[0]
    W = np.zeros((n * p, n * p), dtype=np.complex64)
    for i in range(n):
        for k in range(n):
            for j in range(p):
                for l in range(p):
                    W[p * i + j, p * k + l] = U[i, k] * V[j, l]
    return W

def fourspins(omI, omII, omIII, omIV, gam):
    hbar = 1.
    paulis = paulimatrices()
    iden = np.identity(2)
    SIs = [hbar * kron(kron(kron(pa, iden), iden), iden) / 2 for pa in paulis]
    SIIs = [hbar * kron(kron(kron(iden, pa), iden), iden) / 2 for pa in paulis]
    SIIIs = [hbar * kron(kron(kron(iden, iden), pa), iden) / 2 for pa in paulis]
    SIVs = [hbar * kron(kron(kron(iden, iden), iden), pa) / 2 for pa in paulis]

    SIdotII = sum([SIs[i] @ SIIs[i] for i in range(3)])
    SIdotIII = sum([SIs[i] @ SIIIs[i] for i in range(3)])
    SIIdotIII = sum([SIIs[i] @ SIIIs[i] for i in range(3)])
    SIdotIV = sum([SIs[i] @ SIVs[i] for i in range(3)])
    SIIdotIV = sum([SIIs[i] @ SIVs[i] for i in range(3)])
    SIIIdotIV = sum([SIIIs[i] @ SIVs[i] for i in range(3)])

    H = -omI * SIs[2] - omII * SIIs[2] - omIII * SIIIs[2] - omIV * SIVs[2]

    H = H.real
    return H

if __name__ == '__main__':
    np.set_printoptions(precision=3)
    H = fourspins(1., 2., 3., 4., 0.5)
    qreigvals = np.linalg.eig(H)
    print(qreigvals[0])


[-5. -1. -2.  2. -3.  1.  0.  4. -4.  0. -1.  3. -2.  2.  1.  5.]


# *One can notice that interacing and non-interacing case both eigenvalue are almost equal.*